apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueForm:
                secretKeyRef:
                  name: "mongo-secret"
                  key: "username"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueForm:
                secretKeyRef:
                  name: "mongo-secret"
                  key: "password"
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongo-service"
              # valueForm:
              #   configMapKeyRef:
              #     name: "mongo-express-configmap"
              #     key: "database_url"
